### ISSUE TITLE
Compile error on create-react-app 16.x

### ISSUE THREAD

**Issue by jtnix** [ArjanJ/react-camera#1]
When attempting to use this module after running create-react-app which is currently delivering a 16.3 package.json setup, I get the following error from the react-dom-camera module:

> Failed to compile.
> 
> ./node_modules/react-dom-camera/src/camera/Camera.js
> Module parse failed: Unexpected token (75:21)
> You may need an appropriate loader to handle this file type.
> |   }
> |
> |   captureMediaStream = (event, mediaStream) => {
> |     const ms = mediaStream || this.state.mediaStream;
> |     if (!ms) this.setState({ error: errorTypes.NO_STREAM.type });

I have tried adding stage-0, stage-1, stage-2 and env presets as well as the class-properties plugins to the package.json after ejecting and still get the same error.

Any ideas?

**Comment by ArjanJ** [comment]
Hi @jtnix - thanks for creating the issue! This is a project I didn't really get to finish 😞 There's a lot of changes/improvements needed. If you still want to use it, feel free to submit a PR 🙏 . I can't guarantee i'll work on this again anytime soon.

**Comment by jtnix** [comment]
That's fine, but right now it is unconsumable as a react module on npm; you should consider unpublishing it on npmjs until it is packaged correctly for that platform as a react module. I forked it and spent too much time trying to figure out a correct production compile config with no success, but this is probably because it is an area I am unfamiliar with right now and possibly unable to test in a local linked module environment. 

All I have gathered at this point is the module does not appear to be compiling for commonjs consumption as a sub-module as currently distributed. This may have to do with a number of things, including a missing .npmignore file as it is obvious the src is being distributed as part of the npmjs package, which apparently should not be happening as an npmjs distribution.

**Comment by ArjanJ** [comment]
@jtnix Fair point. Sorry for the inconvenience.

**Comment by ArjanJ** [comment]
I got around to this project again and fixed this issue.
