### ISSUE TITLE
FacingMode not working

### ISSUE THREAD

**Issue by Macro21** [ArjanJ/react-camera#12]
When i press the swap button not change.

Demo fail too.

**Comment by laurencefass** [comment]
+1.

Is this still being maintained and updated?

**Comment by ArjanJ** [comment]
Hello, I'm **not** currently maintaining this project @laurencefass @Macro21

**Comment by laurencefass** [comment]
thanks good to know. is it known fault that swap button doesnt change view?

**Comment by ArjanJ** [comment]
@laurencefass I think the browser API's may have changed since I last touched this project resulting in a few broken things. Feel free to fix the code and submit a PR if you want, or i'm sure there's another package that does this but actually works.
